name: Build Arcanum
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y build-essential cmake pkg-config libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev qttools5-dev-tools libhidapi-dev libusb-1.0-0-dev libprotobuf-dev protobuf-compiler libudev-dev libboost-all-dev
    - name: Build
      run: make release-static -j2
    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: arcanum-linux-x64
        path: build/Linux/master/release/bin/*
